### ISSUE TITLE
Call Google+ API cannot set Authorizer

### ISSUE THREAD

**Issue by andr3a88** [Abhishaker17/GooglePlusSignInMigration#1]
Since i switched from **GPPSignIn** to **GIDSignIn** i can't call "me" or my friends from Google+ API because the authorizer of GTLPlusService. How i can set it?  I tried `[GIDSignIn sharedInstance] currentUser].authentication` but not worked

```
    GTLServicePlus* plusService = [[GTLServicePlus alloc] init];
    plusService.fetcherService.timeout = API_TIMEOUT_INTERVAL;
    [plusService setAuthorizer:[GPPSignIn sharedInstance].authentication];
    GTLQueryPlus *query = [GTLQueryPlus queryForPeopleGetWithUserId:@"me"];
    [plusService executeQuery:query completionHandler:^(GTLServiceTicket *ticket, id object, NSError *error) { 
 }];
```

StackOverflow: http://stackoverflow.com/questions/30841400/share-in-google-using-gtlserviceplus-with-gidauthentication

**Comment by n0shake** [comment]
So, your SO answer seems to have fixed the issue you were facing. Closing.
